version: "1.0"

services:

  selenium:
    image: selenium/standalone-chrome-debug:3.6.0
    depends_on:
      energyefficiency:
        condition: service_healthy
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"

  energyefficiency:
    build: energyefficiency
    ports:
      - "8585:8585"
    command: -m